# Generated by Django 4.1.4 on 2022-12-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
